config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  resources :muscle_groups

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  belongs_to :muscle_group
end

app/models/muscle_group.rb
class MuscleGroup < ActiveRecord::Base
  validates :name, presence: true
  has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # Exercise homepage - evaluate if needed
  def index
  end

  # Display form to create a new exercise
  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save
      redirect_to '/exercises'
    else
      render :new
    end
  end

  # Create the new exercise
  def new
    @exercise = Exercise.new
  end

  # Display a form to edit an exercise
  def edit
  end

  # Show information about an exercise
  def show
  end

  # Update an exercise (save)
  def update

    if @exercise.update(exercise_params)
      redirect_to '/exercises'
    else
      render :edit
    end
  end

  # Delete an exercise
  def destroy
    @exercise.destroy
    redirect_to '/exercises'
  end

  private
  # Strong params
  def exercise_params
    params.require(:exercise).permit(:name, :equipment, :muscle_group_id)
  end

  # Find an exercise
  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

end

app/controllers/muscle_groups_controller.rb
class MuscleGroupsController < ApplicationController
  before_action :set_muscle_group, only: [:show, :edit, :update, :destroy]

  # Index homepage - evaluate if needed
  def index
  end

  # Display form to create a new index
  def create
    @muscle_group = MuscleGroup.new(muscle_group_params)

    if @muscle_group.save
      redirect_to '/muscle_groups'
    else
      render :new
    end
  end

  # Create the new muscle group
  def new
    @muscle_group = MuscleGroup.new
  end

  # Display a form to edit a muscle group
  def edit
  end

  # Show information about a muscle group
  def show
  end

  # Update a muscle group (save)
  def update
    if @muscle_group.update(muscle_group_params)
      redirect_to '/muscle_groups'
    else
      render :edit
    end
  end

  # Delete a muscle group
  def destroy
  end

  private
  # Strong params
  def muscle_group_params
    params.require(:muscle_group).permit(:name)
  end

  # Find a muscle group
  def set_muscle_group
    @muscle_group = MuscleGroup.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/muscle_groups_helper.rb
module MuscleGroupsHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :muscle_group_id %><br>
    <%= f.collection_select(:muscle_group_id, MuscleGroup.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :equipment %><br>
    <%= f.text_area :equipment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Exercise Inventory</h1>

<% Exercise.all.each do |exercise| %>
  <a href='<%= exercise_path(exercise.id) %>'><h2><%= exercise.name %></h2></a>
<% end %>

<%= link_to 'Add New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<h1><%= @exercise.name %></h1>

<p>Equipment - <%= @exercise.equipment %></p>
<p>Muscle Group - <a href="<%= muscle_groups_path(@exercise.muscle_group.id) %>"><%= @exercise.muscle_group.name %></a></p>

<%= link_to 'Back', exercises_path %>
<%= link_to 'Edit', edit_exercise_path %>
<%= link_to "Delete", @excercise, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workouts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/muscle_groups/_form.html.erb
<%= form_for(@muscle_group) do |f| %>
  <% if @muscle_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@muscle_group.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @muscle_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/muscle_groups/edit.html.erb
<h1>Edit a Muscle Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @muscle_group %> |
<%= link_to 'Back', muscle_groups_path %>

app/views/muscle_groups/index.html.erb
<h1>Muscle Groups</h1>

<% MuscleGroup.all.each do |group| %>
  <a href='<%= muscle_group_path(group.id) %>'><h2><%= group.name %></h2></a>
<% end %>

app/views/muscle_groups/new.html.erb
<h1>Add a Muscle Group</h1>

<%= render 'form' %>

<%= link_to 'Back', muscle_groups_path %>

app/views/muscle_groups/show.html.erb
<h1><%= @muscle_group.name %></h1>

<% @muscle_group.exercises.each do |exercise| %>
<p>
  <a href="<%= exercise_path(exercise.id) %>"><%= exercise.name %></a>
</p>
<% end %>

<%= link_to 'Back', muscle_groups_path %>
<%= link_to 'Edit', edit_muscle_group_path %>